[bar.default]
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center"
]
margin_edge = 0
margin_ends = 0
radius = 0
start = [ "launcher", "workspaces" ]

[calendar]
enabled = true

[desktop_widgets]
schema_version = 1
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
enabled = true
icon_size = 40
padding = 4
show_dots = true

[shell]
avatar_path = "/home/r3ddy/.face"
font_family = "Noto Sans"

[theme]
builtin = "Catppuccin"
community_palette = "m3-content"
custom_palette = "ADW"
wallpaper_scheme = "Noctalia"

[wallpaper]
directory = "/home/r3ddy/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/r3ddy/Pictures/Wallpapers/wallpaper.jpg"

    [wallpaper.last]
    path = "/home/r3ddy/Pictures/Wallpapers/wallpaper.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/r3ddy/Pictures/Wallpapers/wallpaper.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/r3ddy/Pictures/Wallpapers/wallpaper.jpg"

[weather]
address = "Bolzano"
refresh_minutes = 60

[widget.clock]
format = "{:%a %d %b %Y %H:%M}"

[widget.control-center]
glyph = "ghost-3-filled"

[widget.network]
show_label = false
