[bar.default]
center = [ "clock" ]
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center"
]
margin_edge = 0
margin_ends = 0
radius = 0
start = [ "launcher", "workspaces" ]

[calendar]
enabled = true

    [calendar.account.personal_google]
    name = "Calendar"
    type = "google"

[desktop_widgets]
schema_version = 1
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
enabled = true
icon_size = 40
magnification_scale = 1.3500000052154064
padding = 4
reserve_space = false
show_dots = true

[location]
address = "Bolzano"

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = false
schema_version = 1
widget_order = [ "lockscreen-login-box@winit", "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 957.0
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 957.0
    output = "eDP-1"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 70.0
    box_width = 400.0
    cx = 464.0
    cy = 863.0
    output = "winit"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[osd.kinds]
media = false

[plugins]
enabled = []

[shell]
avatar_path = "/home/r3ddy/.face"
font_family = "Noto Sans"
polkit_agent = true
settings_show_advanced = true

[theme]
builtin = "Catppuccin"
community_palette = "Tokyo Night Moon"
custom_palette = "Tokyo Night Moon"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "kitty", "niri", "qt" ]
    community_ids = [ "discord", "telegram" ]

[wallpaper]
directory = "/home/r3ddy/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/r3ddy/Pictures/Wallpapers/wallpaper.jpg"

    [wallpaper.last]
    path = "/home/r3ddy/Pictures/Wallpapers/wallpaper.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/r3ddy/Pictures/Wallpapers/wallpaper.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/r3ddy/Pictures/Wallpapers/wallpaper.jpg"

[weather]
address = "Bolzano"
refresh_minutes = 60

[widget.cat]
audio_spectrum = true
rave_mode = true
tappy_mode = true
type = "noctalia/bongocat:cat"
use_mpris_filter = true

[widget.clock]
format = "{:%a %d %b %Y %H:%M}"

[widget.control-center]
glyph = "ghost-3-filled"

[widget.network]
show_label = false
