# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."patrickcanalit-patrickcanalit" = {
    image = "ghcr.io/superredstone/patrickcanal.it:main";
    volumes = [
      "/var/www/patrickcanal.it/db.sqlite3:/app/db.sqlite3:rw"
      "/var/www/patrickcanal.it/local_settings.py:/app/patrickcanal_it/local_settings.py:rw"
      "/var/www/patrickcanal.it/uploads/:/app/uploads/"
    ];
    ports = [
      "8011:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=patrickcanalit"
      "--network=patrickcanalit_default"
    ];
  };
  systemd.services."podman-patrickcanalit-patrickcanalit" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-patrickcanalit_default.service"
    ];
    requires = [
      "podman-network-patrickcanalit_default.service"
    ];
    partOf = [
      "podman-compose-patrickcanalit-root.target"
    ];
    wantedBy = [
      "podman-compose-patrickcanalit-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-patrickcanalit_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f patrickcanalit_default";
    };
    script = ''
      podman network inspect patrickcanalit_default || podman network create patrickcanalit_default
    '';
    partOf = [ "podman-compose-patrickcanalit-root.target" ];
    wantedBy = [ "podman-compose-patrickcanalit-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-patrickcanalit-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
