  # Temporary solution until https://github.com/NixOS/nixpkgs/pull/501051 gets merged
  # TODO: Once merged change also caddy.nix accordingly
# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:
{
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."yamtrack" = {
    image = "ghcr.io/fuzzygrim/yamtrack";
    environmentFiles = [ config.sops.secrets.yamtrack_env.path ];
    volumes = [
      "/var/lib/yamtrack:/yamtrack/db:rw"
    ];
    ports = [
      "8014:8000/tcp"
    ];
    dependsOn = [
      "yamtrack_redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=yamtrack"
      "--network=yamtrack_default"
    ];
  };
  systemd.services."podman-yamtrack" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-yamtrack_default.service"
    ];
    requires = [
      "podman-network-yamtrack_default.service"
    ];
    partOf = [
      "podman-compose-yamtrack-root.target"
    ];
    wantedBy = [
      "podman-compose-yamtrack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."yamtrack_redis" = {
    image = "redis:8-alpine";
    volumes = [
      "yamtrack_redis_data:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=yamtrack_redis"
      "--network=yamtrack_default"
    ];
  };
  systemd.services."podman-yamtrack_redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-yamtrack_default.service"
      "podman-volume-yamtrack_redis_data.service"
    ];
    requires = [
      "podman-network-yamtrack_default.service"
      "podman-volume-yamtrack_redis_data.service"
    ];
    partOf = [
      "podman-compose-yamtrack-root.target"
    ];
    wantedBy = [
      "podman-compose-yamtrack-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-yamtrack_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f yamtrack_default";
    };
    script = ''
      podman network inspect yamtrack_default || podman network create yamtrack_default
    '';
    partOf = [ "podman-compose-yamtrack-root.target" ];
    wantedBy = [ "podman-compose-yamtrack-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-yamtrack_redis_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect yamtrack_redis_data || podman volume create yamtrack_redis_data
    '';
    partOf = [ "podman-compose-yamtrack-root.target" ];
    wantedBy = [ "podman-compose-yamtrack-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-yamtrack-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
